#!/usr/bin/env bash
# This script configures Nginx with a custom 404 page

# This updates and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# This creates a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# This configures Nginx to use the custom 404 page
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    error_page 404 /404.html;

    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOL'

# This creates a symbolic link to enable the custom 404 configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# This tests Nginx configuration and restart
sudo nginx -t
sudo service nginx restart

# This checks if the custom 404 page is served with a 404 status code
response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/non_existent_page)

if [ "$response_code" = "404" ]; then
  echo "Custom 404 page is configured correctly (HTTP 404)."
else
  echo "Custom 404 page may have issues. Expected HTTP 404, but got $response_code."
fi
