#!/usr/bin/env bash
# This is a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
# Format: The user USERNAME is part of the GROUP_NAME gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER_ID INFO

while IFS=':' read -r f1 f2 f3 f4 f5 f6 f7
do
    echo "The user $f1 is part of the $f5 gang, lives in $6 and rides $f7. $f2's place is protected by the passcode $f6, more info about the user here: $f3"
done < "/etc/passwd"
